/*
 *    asn-useful.h
 *
 *    "ASN-USEFUL" ASN.1 module C type definitions and prototypes
 *
 *    This .h file was generated by snacc on Mon May 13 13:12:34 2002
 *
 *    UBC snacc written compiler by Mike Sample
 *
 *    NOTE: This is a machine generated file--editing not recommended
 */


#ifndef _asn_useful_h_
#define _asn_useful_h_


#ifdef __cplusplus
extern "C" {
#endif

typedef AsnOcts ObjectDescriptor; /* [UNIVERSAL 7] IMPLICIT OCTET STRING */

#define BEncObjectDescriptorContent BEncAsnOctsContent

#define BDecObjectDescriptorContent BDecAsnOctsContent

#define PrintObjectDescriptor PrintAsnOcts

#define FreeObjectDescriptor FreeAsnOcts 




typedef AsnOcts VideotexString; /* [UNIVERSAL 21] IMPLICIT OCTET STRING */

AsnLen BEncVideotexString PROTO ((GenBuf *b, VideotexString *v));

#ifdef LDAP_COMPONENT
int BDecVideotexString PROTO ((GenBuf *b, VideotexString *result, AsnLen *bytesDecoded ));
#else
void BDecVideotexString PROTO ((GenBuf *b, VideotexString *result, AsnLen *bytesDecoded, ENV_TYPE env));
#endif

#define BEncVideotexStringContent BEncAsnOctsContent

#define BDecVideotexStringContent BDecAsnOctsContent

#define PrintVideotexString PrintAsnOcts

#define FreeVideotexString FreeAsnOcts 




typedef AsnOcts GraphicString; /* [UNIVERSAL 25] IMPLICIT OCTET STRING */

AsnLen BEncGraphicString PROTO ((GenBuf *b, GraphicString *v));
#ifdef LDAP_COMPONENT
int BDecGraphicString PROTO ((GenBuf *b, GraphicString *result, AsnLen *bytesDecoded ));
#else
void BDecGraphicString PROTO ((GenBuf *b, GraphicString *result, AsnLen *bytesDecoded, ENV_TYPE env));
#endif
#define BEncGraphicStringContent BEncAsnOctsContent

#define BDecGraphicStringContent BDecAsnOctsContent

#define PrintGraphicString PrintAsnOcts

#define FreeGraphicString FreeAsnOcts 




/*typedef AsnOcts VisibleString;  [UNIVERSAL 26] IMPLICIT OCTET STRING */

/*AsnLen BEncVisibleString PROTO ((GenBuf *b, VisibleString *v));*/

/*void BDecVisibleString PROTO ((GenBuf *b, VisibleString *result, AsnLen *bytesDecoded, ENV_TYPE env));*/
/*#define BEncVisibleStringContent BEncAsnOctsContent*/

/*#define BDecVisibleStringContent BDecAsnOctsContent */

#define PrintVisibleString PrintAsnOcts

#define FreeVisibleString FreeAsnOcts 




typedef AsnOcts ISO646String; /* [UNIVERSAL 26] IMPLICIT OCTET STRING */

AsnLen BEncISO646String PROTO ((GenBuf *b, ISO646String *v));

#ifdef LDAP_COMPONENT
int BDecISO646String PROTO ((GenBuf *b, ISO646String *result, AsnLen *bytesDecoded));
#else
void BDecISO646String PROTO ((GenBuf *b, ISO646String *result, AsnLen *bytesDecoded, ENV_TYPE env));
#endif
#define BEncISO646StringContent BEncAsnOctsContent

#define BDecISO646StringContent BDecAsnOctsContent

#define PrintISO646String PrintAsnOcts

#define FreeISO646String FreeAsnOcts 




typedef AsnOcts GeneralString; /* [UNIVERSAL 27] IMPLICIT OCTET STRING */

AsnLen BEncGeneralString PROTO ((GenBuf *b, GeneralString *v));

#ifdef LDAP_COMPONENT
int BDecGeneralString PROTO ((GenBuf *b, GeneralString *result, AsnLen *bytesDecoded ));
#else
void BDecGeneralString PROTO ((GenBuf *b, GeneralString *result, AsnLen *bytesDecoded, ENV_TYPE env));
#endif
#define BEncGeneralStringContent BEncAsnOctsContent

#define BDecGeneralStringContent BDecAsnOctsContent

#define PrintGeneralString PrintAsnOcts

#define FreeGeneralString FreeAsnOcts 




typedef AsnOcts UTCTime; /* [UNIVERSAL 23] IMPLICIT OCTET STRING */

AsnLen BEncUTCTime PROTO ((GenBuf *b, UTCTime *v));

#ifdef LDAP_COMPONENT
int BDecUTCTime PROTO ((GenBuf *b, UTCTime *result, AsnLen *bytesDecoded));
#else
void BDecUTCTime PROTO ((GenBuf *b, UTCTime *result, AsnLen *bytesDecoded, ENV_TYPE env));
#endif
#define BEncUTCTimeContent BEncAsnOctsContent

#define BDecUTCTimeContent BDecAsnOctsContent

#define PrintUTCTime PrintAsnOcts

#define FreeUTCTime FreeAsnOcts 




typedef AsnOcts GeneralizedTime; /* [UNIVERSAL 24] IMPLICIT OCTET STRING */

AsnLen BEncGeneralizedTime PROTO ((GenBuf *b, GeneralizedTime *v));

#ifdef LDAP_COMPONENT
int BDecGeneralizedTime PROTO ((GenBuf *b, GeneralizedTime *result, AsnLen *bytesDecoded));
#else
void BDecGeneralizedTime PROTO ((GenBuf *b, GeneralizedTime *result, AsnLen *bytesDecoded, ENV_TYPE env));
#endif
#define BEncGeneralizedTimeContent BEncAsnOctsContent

#define BDecGeneralizedTimeContent BDecAsnOctsContent

#define PrintGeneralizedTime PrintAsnOcts

#define FreeGeneralizedTime FreeAsnOcts 




typedef struct EXTERNALChoice /* CHOICE */
{
    enum EXTERNALChoiceChoiceId
    {
        EXTERNALCHOICE_SINGLE_ASN1_TYPE,
        EXTERNALCHOICE_OCTET_ALIGNED,
        EXTERNALCHOICE_ARBITRARY
    } choiceId;
    union EXTERNALChoiceChoiceUnion
    {
    AsnOcts* single_ASN1_type; /* [0] OCTET STRING */
    AsnOcts* octet_aligned; /* [1] IMPLICIT OCTET STRING */
    AsnBits* arbitrary; /* [2] IMPLICIT BIT STRING */
    } a;
} EXTERNALChoice;

AsnLen BEncEXTERNALChoiceContent PROTO ((GenBuf *b, EXTERNALChoice *v));

#ifdef LDAP_COMPONENT
int BDecEXTERNALChoiceContent PROTO ((GenBuf *b, AsnTag tagId0, AsnLen elmtLen0, EXTERNALChoice *v, AsnLen *bytesDecoded ));
#else
void BDecEXTERNALChoiceContent PROTO ((GenBuf *b, AsnTag tagId0, AsnLen elmtLen0, EXTERNALChoice *v, AsnLen *bytesDecoded, ENV_TYPE env));
#endif


void PrintEXTERNALChoice PROTO ((FILE* f, EXTERNALChoice *v, unsigned int indent));
void FreeEXTERNALChoice PROTO ((EXTERNALChoice *v));





typedef struct EXTERNAL /* [UNIVERSAL 8] IMPLICIT SEQUENCE */
{
    AsnOid direct_reference; /* OBJECT IDENTIFIER OPTIONAL */
    AsnInt* indirect_reference; /* INTEGER OPTIONAL */
    ObjectDescriptor data_value_descriptor; /* ObjectDescriptor OPTIONAL */
    struct EXTERNALChoice* encoding; /* EXTERNALChoice */
} EXTERNAL;

AsnLen BEncEXTERNAL PROTO ((GenBuf *b, EXTERNAL *v));

#ifdef LDAP_COMPONENT
int BDecEXTERNAL PROTO ((GenBuf *b, EXTERNAL *result, AsnLen *bytesDecoded ));
#else
void BDecEXTERNAL PROTO ((GenBuf *b, EXTERNAL *result, AsnLen *bytesDecoded, ENV_TYPE env));
#endif
AsnLen BEncEXTERNALContent PROTO ((GenBuf *b, EXTERNAL *v));

#ifdef LDAP_COMPONENT
int BDecEXTERNALContent PROTO ((GenBuf *b, AsnTag tagId0, AsnLen elmtLen0, EXTERNAL *v, AsnLen *bytesDecoded ));
#else
void BDecEXTERNALContent PROTO ((GenBuf *b, AsnTag tagId0, AsnLen elmtLen0, EXTERNAL *v, AsnLen *bytesDecoded, ENV_TYPE env));
#endif


void PrintEXTERNAL PROTO ((FILE* f, EXTERNAL *v, unsigned int indent));
void FreeEXTERNAL PROTO ((EXTERNAL *v));


#ifdef __cplusplus
}
#endif


#endif /* conditional include of asn-useful.h */
