
#include "asn-incl.h"
/*
 *    any.h
 *    "ANY-TEST" ASN.1 module C type definitions and prototypes
 *    This .h file was generated by Coral WinSnacc on Thu Oct  7 09:01:53 2004
 *    Coral WinSnacc written compiler by Deepak Gupta
 *    NOTE: This is a machine generated file--editing not recommended
 */

#ifndef _any_h_
#define _any_h_




#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#pragma warning( disable : 4101 )
#endif
typedef enum ANY_TESTAnyId
{
    intId_ANY_ID = 0,
    boolId_ANY_ID = 1,
    octsId_ANY_ID = 2,
    bitsId_ANY_ID = 3,
    realId_ANY_ID = 4,
    intOid_ANY_ID = 5,
    boolOid_ANY_ID = 6,
    octsOid_ANY_ID = 7,
    bitsOid_ANY_ID = 8,
    realOid_ANY_ID = 9} ANY_TESTAnyId;


void InitAnyANY_TEST();

typedef AsnBits BitsId; /* [PRIVATE 1] BIT STRING */

void BDecBitsId PROTO ((GenBuf * b, BitsId *result, AsnLen *bytesDecoded, ENV_TYPE env));
#define BDecBitsIdContent BDecAsnBitsContent


typedef AsnOcts OctsId; /* [PRIVATE 2] IMPLICIT OCTET STRING */

void BDecOctsId PROTO ((GenBuf * b, OctsId *result, AsnLen *bytesDecoded, ENV_TYPE env));
#define BDecOctsIdContent BDecAsnOctsContent


typedef struct AttrValue1 /* SEQUENCE */
{
	AsnInt id; /* INTEGER */
	AsnAnyDefinedBy anyDefBy; /* ANY DEFINED BY id */
} AttrValue1;

void BDecAttrValue1Content PROTO ((GenBuf * b, AsnTag tagId0, AsnLen elmtLen0, AttrValue1 *v, AsnLen *bytesDecoded, ENV_TYPE env));



typedef struct AttrValue2 /* SEQUENCE */
{
	AsnOid id; /* OBJECT IDENTIFIER */
	AsnAnyDefinedBy anyDefBy; /* ANY DEFINED BY id */
} AttrValue2;

void BDecAttrValue2Content PROTO ((GenBuf * b, AsnTag tagId0, AsnLen elmtLen0, AttrValue2 *v, AsnLen *bytesDecoded, ENV_TYPE env));



typedef AsnList TSeq1; /* SEQUENCE OF AttrValue1 */

void BDecTSeq1Content PROTO ((GenBuf * b, AsnTag tagId0, AsnLen elmtLen0, TSeq1 *v, AsnLen *bytesDecoded, ENV_TYPE env));



typedef AsnList TSeq2; /* SEQUENCE OF AttrValue2 */

void BDecTSeq2Content PROTO ((GenBuf * b, AsnTag tagId0, AsnLen elmtLen0, TSeq2 *v, AsnLen *bytesDecoded, ENV_TYPE env));



typedef struct AnyTestType /* SEQUENCE */
{
	TSeq1* intMap; /* TSeq1 */
	TSeq2* oidMap; /* TSeq2 */
} AnyTestType;

void BDecAnyTestType PROTO ((GenBuf * b, AnyTestType *result, AsnLen *bytesDecoded, ENV_TYPE env));
void BDecAnyTestTypeContent PROTO ((GenBuf * b, AsnTag tagId0, AsnLen elmtLen0, AnyTestType *v, AsnLen *bytesDecoded, ENV_TYPE env));



/* ========== Object Declarations ========== */


/* ========== Object Set Declarations ========== */
#ifdef __cplusplus
extern "C" {
#endif

#endif /* conditional include of any.h */
